stages:
  data_ingestion:
    cmd: |
      python src/alzheimer_disease/pipeline/s01_data_ingestion.py
    deps:
      - src/alzheimer_disease/pipeline/s01_data_ingestion.py
      - src/alzheimer_disease/entity/artifacts_entity.py
      - src/alzheimer_disease/entity/config_entity.py
    outs:
      - "artifacts/data_ingestion/test"
      - "artifacts/data_ingestion/train"

  data_validation:
    cmd: |
      python src/alzheimer_disease/pipeline/s02_data_validation.py
    deps:
      - src/alzheimer_disease/pipeline/s02_data_validation.py
      - src/alzheimer_disease/entity/artifacts_entity.py
      - src/alzheimer_disease/entity/config_entity.py
      - "artifacts/data_ingestion/test"
      - "artifacts/data_ingestion/train"
    outs:
      - "artifacts/data_validation/status.txt"

  model_training:
    cmd: |
      python src/alzheimer_disease/pipeline/s03_model_trainer.py
    deps:
      - src/alzheimer_disease/pipeline/s03_model_trainer.py
      - src/alzheimer_disease/entity/config_entity.py
      - "artifacts/data_validation/status.txt"
      - "artifacts/data_ingestion/train"
    outs:
      - "artifacts/model_trainer/alzeimer_model.h5"
      - "artifacts/model_trainer/checkpoints"
      - "artifacts/model_trainer/evaluation_results.json"

      
      

  evaluation:
    cmd: |
      python src/alzheimer_disease/pipeline/s04_model_eval.py
    deps:
      - src/alzheimer_disease/entity/config_entity.py
      - "artifacts/model_trainer/alzeimer_model.h5"
      - "artifacts/data_ingestion/test"
      -  saved_models/1/model
      

  model_pusher:
    cmd: |
      python src/alzheimer_disease/pipeline/s05_model_pusher.py
    deps:
      - src/alzheimer_disease/pipeline/s05_model_pusher.py
      - src/alzheimer_disease/entity/config_entity.py
      - saved_models/1/model
      - "artifacts/model_trainer/alzeimer_model.h5"
      
    
