stages:
  data_ingestion:
    cmd: python src/alzheimer_disease/components/data_ingestion.py
    deps:
      - src/alzheimer_disease/pipeline/s01_data_ingestion.py
 
      
    outs:
      - artifacts1/data_ingestion/test
      - artifacts1/data_ingestion/train

  validation:
    cmd: python src/alzheimer_disease/components/data_validation.py    
    deps:
      - src/alzheimer_disease/pipeline/s02_data_validation.py
   
     
    outs:
      -  artifacts1/data_validation/status.txt

  model_training:
    cmd: python src/alzheimer_disease/components/model_trainer.py
    deps:
      - src/alzheimer_disease/pipeline/s03_model_trainer.py
      
     
    outs:
      -  artifacts1/model_trainer/alzeimer_model.h5   
      -  artifacts1/model_trainer/evaluation_results.json
      -  artifacts1/model_trainer/checkpoints

  evaluation:
    cmd: python src/alzheimer_disease/components/model_eval.py
    deps:
      - src/alzheimer_disease/pipeline/s04_model_eval.py
    
   
    

  pusher:
    cmd: python src/alzheimer_disease/components/model_pusher.py
    deps:
      - src/alzheimer_disease/pipeline/s05_model_pusher.py
    
  
    outs:
      -  artifacts1/model_pusher/alzeimer_model.h5



# Add other stages' parameters here
