import os
import tensorflow as tf

ARTIFACTS_DIR: str = "artifacts"


data_ingestion:
  DATA_INGESTION_DIR_NAME: str = "data_ingestion"
  DATA_INGESTION_FEATURE_STORE_DIR: str = "feature_store"
  DATA_BASE_NAME: str = "alzeimer_database-1"
  OUTPUT_FOLDER_PATH: str= os.path.join("data")
  TRAIN_COLLECTION_NAME: str = "train"
  TEST_COLLECTION_NAME: str = "test"



data_valudation:
  DATA_VALIDATION_DIR_NAME: str = "data_validation"
  DATA_VALIDATION_STATUS_FILE: str = 'status.txt'
  DATA_VALIDATION_ALL_REQUIRED_FILES: str = ["train", "test"]


model_trainer:
  MODEL_TRAINER_DIR_NAME: str = "model_trainer"
  MODEL_TRAINER_FEATURE_STORE_DIR: str = "feature_store"
  MODEL_NAME: str = "alzeimer_model.h5"
  MODEL_TRAINER_BATCH_SIZE : int = 32
  MODEL_TRAINER_EPOCHS : int = 1
  MODEL_CHECKPOINT_DIR_NAME: str =  "checkpoints"
  IMAGE_SIZE: tuple = (256, 256)
  CHANNELS: int = 3
  INPUT_SHAPE: tuple = (IMAGE_SIZE, IMAGE_SIZE, CHANNELS)
  CLASSES: int = 5
  VALIDATION_SPLIT: int = 0.2
  OPTIMIZER: str = "adam"
  PATIENCE: int = 10
  MODEL_TEST: str = "Tensorflow_test"
  EXPECTED_SCORE_THRESHOLD : float = 0.1
  PREDICTION_REPORT: str = 'evaluation_results.json'
  OVERFITTING_THRESHOLD: float = 0.30




model_pusher:
  CHANGE_THRESHOLD: float = 0.05